### PR TITLE
Update GoogleParser for maneuver management

### PR DESCRIPTION
**Pull request by vincenzoiacovone**
Updated for set maneuver fields in segments

### CODE REVIEW

**Comment by jd-alexander** [comment]
Can you try to figure out why the build is failing. Look at the error log from Travis CI

library:compileDebugJava/home/travis/build/jd-alexander/Google-Directions-Android/library/src/main/java/com/directions/route/GoogleParser.java:114: error: cannot find symbol
segment.setManeuver(step.getString("maneuver"));
                               ^
  symbol:   method setManeuver(String)
  location: variable segment of type Segment

**Comment by vincenzoiacovone** [comment]
Hi, the building fail because this pull request #56 should be merged with #55 to use method setManeuver(string) in Segment.java (committed on #55)
